export const MOCK_MOVIES = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "Pulp Fiction",
  "The Lord of the Rings: The Return of the King",
  "Schindler's List",
  "Forrest Gump",
  "Inception",
  "The Matrix",
  "Fight Club",
  "The Empire Strikes Back",
  "The Godfather: Part II",
  "Goodfellas",
  "The Lord of the Rings: The Fellowship of the Ring",
  "One Flew Over the Cuckoo's Nest",
  "Interstellar",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "Parasite",
  "The Green Mile",
  "The Lion King",
  "Gladiator",
  "The Departed",
  "The Prestige",
  "Back to the Future",
  "Django Unchained",
  "Braveheart",
  "Titanic",
  "Avatar",
  "Avengers: Endgame",
  "The Lord of the Rings: The Two Towers",
  "Star Wars",
  "Jurassic Park",
  "The Terminator",
  "Alien",
  "Blade Runner",
  "The Shining",
  "The Usual Suspects",
  "The Pianist",
  "A Beautiful Mind",
  "Whiplash",
  "The Wolf of Wall Street",
  "12 Years a Slave",
  "The Social Network",
  "The Truman Show",
  "Mad Max: Fury Road",
  "Indiana Jones: Raiders of the Lost Ark",
  "E.T. the Extra-Terrestrial",
  "Casablanca",
  "City of God",
  "Memento",
  "American History X",
  "The Grand Budapest Hotel",
  "Inglourious Basterds",
  "No Country for Old Men",
  "The Big Lebowski",
  "Slumdog Millionaire",
  "Se7en",
  "The Sixth Sense",
  "La La Land",
  "The Great Dictator",
  "2001: A Space Odyssey",
  "Spirited Away",
  "The Intouchables",
  "Gone with the Wind",
  "Chinatown",
  "Schindler's List",
  "The Good, the Bad and the Ugly",
  "Taxi Driver",
  "Apocalypse Now",
  "The Thing",
  "Full Metal Jacket",
  "Platoon",
  "Die Hard",
  "The Exorcist",
  "Psycho",
  "Jaws",
  "Rocky",
  "Raging Bull",
  "The Godfather: Part III",
  "The Silence of the Lambs",
  "A Clockwork Orange",
  "Good Will Hunting",
  "Scarface",
  "The Dark Knight Rises",
  "The Imitation Game",
  "Spotlight",
  "The King's Speech",
  "Amélie",
  "Eternal Sunshine of the Spotless Mind",
  "Oldboy",
  "Requiem for a Dream",
  "Life Is Beautiful",
  "The Hunt",
  "Pan's Labyrinth",
  "Crouching Tiger, Hidden Dragon",
  "Amadeus",
  "Lawrence of Arabia",
  "The Great Escape",
  "Ben-Hur",
  "12 Angry Men",
  "It's a Wonderful Life",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
];
